apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-compressor-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-compressor
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Object
    object:
      metric:
        name: video_compressor_gpu_avg
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: video-compressor
      target:
        type: Value
        value: "50"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10